import type {
    InferGetStaticPropsType,
    GetStaticProps,
    GetStaticPaths,
  } from 'next';
import Head from 'next/head';
import styles from '@/styles/ProductDetail.module.scss';
import { mockProductsData } from '@/mockAPI/mockData';
import { mockGetProductDetailInfoAPI } from '@/mockAPI';
import type { ProductDetailInfo } from '@/mockAPI/types';
import ProductDetailCard from '@/components/productDetailCard/productDetailCard';
import Image from 'next/image';

export const getStaticPaths = (async () => {
    const paths = mockProductsData.map(({productId}) => {
        return {
            params: {
                productId,
            },
        };
    });

    return {
        paths,
        fallback: false,
    }
}) satisfies GetStaticPaths;

export const getStaticProps = (async ({params}) => {
    if (!params) {
        return { props: { product: {} as ProductDetailInfo } };
    }
    const product = await mockGetProductDetailInfoAPI(params.productId);

    return { props: { product } }
}) satisfies GetStaticProps<{
    product: ProductDetailInfo,
}, {productId: string}>;

export default function ProductDetail({
    product,
}: InferGetStaticPropsType<GetStaticProps>) {
    const {productId, productName, productImage} = product;

    if (!productId) {
        return <div>查无此商品</div>
    }

    return (
        <>
            <Head>
                <title>Shopping - Produect detail</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.productDetail}>
                <section className='content'>
                    <ProductDetailCard product={product} />
                </section>
                <section className='product-description'>
                    <h1>商品详情</h1>
                    <h2>{productName}</h2>
                    <Image src={productImage} width={680} height={850} alt='product iamge' />
                </section>
            </main>
        </>
    )
}