import Head from 'next/head';
import Link from 'next/link';
import type { InferGetServerSidePropsType, GetServerSideProps } from 'next';
import styles from '@/styles/Products.module.scss';
import { mockGetProductsAPI } from '@/mockAPI';
import type { ProductInfo } from '@/mockAPI/types';
import ProductCard from '@/components/productCard/ProductCard';

export const getServerSideProps: GetServerSideProps = async () => {
    const products = await mockGetProductsAPI();

    return {
        props: {
            products,
        },
    };
}

export default function Products({
    products,
}: InferGetServerSidePropsType<GetServerSideProps>) {

    const renderProductList = () => {
        return products.map((product: ProductInfo) => {
            return (
                <Link href={`/products/detail/${product.productId}`} key={`productKey-${product.productId}`}>
                    <ProductCard product={product} />
                </Link>
            );
        });
    }

    return (
        <>
            <Head>
                <title>Shopping - Produect list</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.products}>
                <div className='content'>
                    {renderProductList()}
                </div>
            </main>
        </>
    )
}