import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import BgIndex from '@/asstes/bg-index.jpg';
import BgGG1 from '@/asstes/bg-goods-guidance-1.jpg';
import BgGG2 from '@/asstes/bg-goods-guidance-2.jpg';
import BgGG3 from '@/asstes/bg-goods-guidance-3.jpg';
import BgGG4 from '@/asstes/bg-goods-guidance-4.jpg';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Shopping</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <Image className='slogen-bg' src={BgIndex} alt='bg image' />
                <section className='goods-guidance'>
                    <div className='goods-guidance__row'>
                        <div className='goods-guidance-card'>
                            <Link href={'/products'}>
                                <Image className='card__image' src={BgGG2} alt='goods guidance bg' />
                                <p className='card-title'>女装新品</p>
                            </Link>
                        </div>
                        <div className='goods-guidance-card'>
                            <Image className='card__image' src={BgGG1} alt='goods guidance bg' />
                            <p className='card-title'>男装新品</p>
                        </div>
                    </div>
                    <div className='goods-guidance__row'>
                        <div className='goods-guidance-card'>
                            <Image className='card__image' src={BgGG3} alt='goods guidance bg' />
                            <p className='card-title'>情侣新品</p>
                        </div>
                        <div className='goods-guidance-card'>
                            <Image className='card__image' src={BgGG4} alt='goods guidance bg' />
                            <p className='card-title'>儿童新品</p>
                        </div>
                    </div>
                </section>
            </main>
        </>
    );
}
